# Generated by Django 5.0.1 on 2024-02-05 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
