# Generated by Django 5.0.1 on 2024-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_questionanwer_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnwer',
            new_name='QuestionAnswer',
        ),
    ]
